### ISSUE TITLE
tmweb and network-mode host

### ISSUE THREAD

**Issue by kforner** [dennyverbeeck/transmart-docker#6]
Initially I wanted to remove the tmweb apache proxy because in the end transmart is going to be under another apache proxy of mine. 
Then I realized that the tmapp was speaking ajp, which makes it hard to check. 
I then decided to use tmweb, to be able to check/debug transmart locally on http (and export it via https via my proxy).

The problem is that tmweb is setup in network-mode host, which is problematic:

- you need to have the port 80 available (I don't)
- you need to export the DB port to the host (this one is benign).

Setting up in the _normal way_ seems to be not so straightforward since the vhosts have to be modified also. 
My question is: why using **network-mode host** ? It is less flexible, so I suppose there other elements to take into account...

**Comment by dennyverbeeck** [comment]
Hi Karl,

As pointed out in the readme, the default settings are geared towards running these services on a server. The readme also provides a section on [running a local instance](https://github.com/dennyverbeeck/transmart-docker#running-a-local-instance). So a couple of thoughts:

- The choice to use ajp instead of http is purely for performance reasons. The ajp connector allows apache and tomcat to speak binary to eachother, rather than cleartext. But in a regular setup, TM will not have many concurrent users, so i doubt it will make much of a difference. The tmapp container still has the regular http connector as well. You can easily export the 8080 port of the tmapp container and have your own proxy talk to that over http, and leave out tmweb altogether
- Host mode networking is also desirable for tmweb when running on a server. When using tmweb in bridged networking, you don't see the IP's of the clients connecting to you (or at least i don't know of a way to easily accomplish this). If you want to keep an eye on traffic using tmweb's logs, this is a problem.
- You don't actually need to export the DB port to the local host. Only tmapp's 8009 or 8080 port needs to be exposed to localhost when tmweb is in host network mode. I exported the DB port to localhost by default, because this allows administrators to connect to it through an SSH tunnel with tools on their local machine. Again, this is a choice motivated by the assumption this will all be running on a remote server.

**Comment by kforner** [comment]
>  When using tmweb in bridged networking, you don't see the IP's of the clients connecting to you

ok, in my case I can have those via my apache proxy.

> You don't actually need to export the DB port to the local host. 

My mistake, I meant the transmart port (ajp or http).

Thanks for your reply,  I understand now.
